global:
  scrape_interval: 5s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - host.docker.internal:9100
 - job_name: jenkins
   metrics_path: /prometheus/
   scrape_interval: 300s
   scrape_timeout: 30s
   static_configs:
    - targets: 
       - host.docker.internal:8080
